// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	adminextra "zephyr-go/app/gateway/internal/handler/adminextra"
	auth "zephyr-go/app/gateway/internal/handler/auth"
	dept "zephyr-go/app/gateway/internal/handler/dept"
	identity "zephyr-go/app/gateway/internal/handler/identity"
	menu "zephyr-go/app/gateway/internal/handler/menu"
	post "zephyr-go/app/gateway/internal/handler/post"
	role "zephyr-go/app/gateway/internal/handler/role"
	user "zephyr-go/app/gateway/internal/handler/user"
	"zephyr-go/app/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodPost, Path: "/login", Handler: auth.LoginHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/logout", Handler: auth.LogoutHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/refresh", Handler: auth.RefreshHandler(serverCtx)},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodPost, Path: "/remove", Handler: dept.DeptRemoveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/save", Handler: dept.DeptSaveHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/tree", Handler: dept.DeptTreeHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/update", Handler: dept.DeptUpdateHandler(serverCtx)},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/system/dept"),
	)

	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodGet, Path: "/info", Handler: identity.GetUserInfoHandler(serverCtx)},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodGet, Path: "/tree", Handler: menu.MenuTreeHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/list", Handler: adminextra.MenuListHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/detail", Handler: adminextra.MenuDetailHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/save", Handler: adminextra.MenuSaveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/update", Handler: adminextra.MenuUpdateHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/remove", Handler: adminextra.MenuRemoveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/status", Handler: adminextra.MenuStatusHandler(serverCtx)},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/system/menu"),
	)

	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodGet, Path: "/list", Handler: post.PostPageHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/remove", Handler: post.PostRemoveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/save", Handler: post.PostSaveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/status", Handler: post.PostStatusHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/update", Handler: post.PostUpdateHandler(serverCtx)},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/system/post"),
	)

	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodGet, Path: "/list", Handler: role.RolePageHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/remove", Handler: role.RoleRemoveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/submit", Handler: role.RoleSubmitHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/updateStatus", Handler: role.RoleUpdateStatusHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/detail", Handler: adminextra.RoleDetailHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/menuTree", Handler: adminextra.RoleMenuTreeHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/assignMenus", Handler: adminextra.RoleAssignMenusHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/dataScope", Handler: adminextra.RoleDataScopeHandler(serverCtx)},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/system/role"),
	)

	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodGet, Path: "/list", Handler: user.UserListHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/remove", Handler: user.UserRemoveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/resetPassword", Handler: user.UserResetPasswordHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/submit", Handler: user.UserSubmitHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/updateStatus", Handler: user.UserUpdateStatusHandler(serverCtx)},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/system/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodGet, Path: "/login-log/list", Handler: adminextra.LoginLogListHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/login-log/remove", Handler: adminextra.LoginLogRemoveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/login-log/clear", Handler: adminextra.LoginLogClearHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/op-log/list", Handler: adminextra.OperationLogListHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/op-log/detail", Handler: adminextra.OperationLogDetailHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/op-log/remove", Handler: adminextra.OperationLogRemoveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/op-log/clear", Handler: adminextra.OperationLogClearHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/online/list", Handler: adminextra.OnlineListHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/online/kickout", Handler: adminextra.OnlineKickoutHandler(serverCtx)},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/security"),
	)

	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodGet, Path: "/server", Handler: adminextra.ServerMetricsHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/cache", Handler: adminextra.CacheMetricsHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/datasource", Handler: adminextra.DatasourceMetricsHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/cron/list", Handler: adminextra.CronListHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/cron/handlers", Handler: adminextra.CronHandlersHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/cron/save", Handler: adminextra.CronSaveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/cron/status", Handler: adminextra.CronStatusHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/cron/remove", Handler: adminextra.CronRemoveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/cron/run", Handler: adminextra.CronRunHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/cron/logs", Handler: adminextra.CronLogsHandler(serverCtx)},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/monitor"),
	)

	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodGet, Path: "/dict/type/list", Handler: adminextra.DictTypeListHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/dict/type/save", Handler: adminextra.DictTypeSaveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/dict/type/remove", Handler: adminextra.DictTypeRemoveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/dict/type/status", Handler: adminextra.DictTypeStatusHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/dict/data/list", Handler: adminextra.DictDataListHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/dict/data/save", Handler: adminextra.DictDataSaveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/dict/data/remove", Handler: adminextra.DictDataRemoveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/dict/data/status", Handler: adminextra.DictDataStatusHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/params/list", Handler: adminextra.ParamsListHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/params/save", Handler: adminextra.ParamsSaveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/params/remove", Handler: adminextra.ParamsRemoveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/params/refresh-cache", Handler: adminextra.ParamsRefreshCacheHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/files/list", Handler: adminextra.FilesListHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/files/upload", Handler: adminextra.FilesUploadHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/files/download", Handler: adminextra.FilesDownloadHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/files/remove", Handler: adminextra.FilesRemoveHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/notices/list", Handler: adminextra.NoticesListHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/notices/save", Handler: adminextra.NoticesSaveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/notices/remove", Handler: adminextra.NoticesRemoveHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/notices/publish", Handler: adminextra.NoticesPublishHandler(serverCtx)},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/infrastructure"),
	)

	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodGet, Path: "/codegen/list", Handler: adminextra.CodegenListHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/codegen/preview", Handler: adminextra.CodegenPreviewHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/codegen/download", Handler: adminextra.CodegenDownloadHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/api-doc/info", Handler: adminextra.ApiDocInfoHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/sql/status", Handler: adminextra.SQLStatusHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/sql/execute", Handler: adminextra.SQLExecuteHandler(serverCtx)},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/devtools"),
	)
}
